In [12]:
import pandas as pd

pd.set_option("display.max_columns", None)  # Show all columns
pd.set_option("display.width", None)        # Use full width of the console
pd.set_option("display.max_colwidth", None)  # Show full content in each column

import ast

In [14]:
# Check bins of confidence: 1) count how many observations had 5 vs 4 vs 3 etc models that aligned and 2) count distribution of probabilities (note that these probs are coming from the calibratred probabilties, so all good there)

dfs = []
paths = ["/home/csutter/DRIVE-clean/ensembling/data_preds/modelFinal_OT0.csv",
"/home/csutter/DRIVE-clean/ensembling/data_preds/modelFinal_OT1.csv",
"/home/csutter/DRIVE-clean/ensembling/data_preds/modelFinal_OT2.csv",
"/home/csutter/DRIVE-clean/ensembling/data_preds/modelFinal_OT3.csv",
"/home/csutter/DRIVE-clean/ensembling/data_preds/modelFinal_OT4.csv",
"/home/csutter/DRIVE-clean/ensembling/data_preds/modelFinal_OT5.csv"]

for p in paths:
    d = pd.read_csv(p)
    dfs.append(d)

df = pd.concat(dfs)

print(len(df))


# for i in df.columns:
#     print(i)



def consistency_row(row):
    cat = row["select"]
    dic = row["dict_catAsKeys_countAsValues"]
    dic = ast.literal_eval(dic)  # safely convert string → dict
    ct = dic[cat]
    return ct

df["consistency"] =df.apply(consistency_row, axis =1 )

display(df.head(4))

21489

,Unnamed: 0,index,Unnamed: 0.2,Unnamed: 0.1,m0_innerPhase,outerPhase,img_name,img_orig,site,img_cat,foldnum,timeofday,timeofevent,m0_calib_prob_dry,m0_calib_prob_poor_viz,m0_calib_prob_snow,m0_calib_prob_snow_severe,m0_calib_prob_wet,m0_calib_prob,img_orig_hrrr,img_index,Latitude,Longitude,yr,mo,day,date,time,ymd,date_and_time_str,date_and_time_dt,date_and_time_dt_round,date_and_time_dt_init,init_hr,init_year,init_month,init_day,init_yyyymmdd,hrrr_file,HRRR_latlon,HRRR_distkm,time.1,valid_time,latitude,longitude,t2m,pt,sh2,d2m,r2,u10,v10,si10,asnow,tp,orog,cape,mslma,dswrf,dlwrf,tcc,gh,dpt,atmosphere,isobaricInhPa,uavg,o_prob_dry,o_prob_poor_viz,o_prob_snow,o_prob_snow_severe,o_prob_wet,o_pred,o_prob,classifier_TF,classifier_01,o_prob_calib,m0_calib_pred,m1_calib_prob_dry,m1_calib_prob_poor_viz,m1_calib_prob_snow,m1_calib_prob_snow_severe,m1_calib_prob_wet,m1_calib_pred,m1_calib_prob,m2_calib_prob_dry,m2_calib_prob_poor_viz,m2_calib_prob_snow,m2_calib_prob_snow_severe,m2_calib_prob_wet,m2_calib_pred,m2_calib_prob,m3_calib_prob_dry,m3_calib_prob_poor_viz,m3_calib_prob_snow,m3_calib_prob_snow_severe,m3_calib_prob_wet,m3_calib_pred,m3_calib_prob,m4_calib_prob_dry,m4_calib_prob_poor_viz,m4_calib_prob_snow,m4_calib_prob_snow_severe,m4_calib_prob_wet,m4_calib_pred,m4_calib_prob,list_5preds,list_5probs,dict_catAsKeys_modelAsValues,dict_catAsKeys_countAsValues,dict_catAsKeys_probsAsValues,dict_mostConfident_singleModel,ensembleAvg_dry,ensembleAvg_snow,ensembleAvg_snow_severe,ensembleAvg_wet,ensembleAvg_poor_viz,ensembleAvg_pred,ensembleAvg_predprob,ensembleMode_pred,ensembleMaxConf_pred,methodalign_1_2,methodalign_1_3,methodalign_2_3,select,decision,select_correct,ok_select,consistency
0,0,16723,16723,16723,NAOuterTest,outerTest,390_at_Lyell_Ave__Unknown__Skyline_6117_2022-01-25-00:00:10.jpg,/home/csutter/DRIVE/site_analysis/outsideFinalTestDataset/images/Skyline_6117/snow/390_at_Lyell_Ave__Unknown__Skyline_6117_2022-01-25-00:00:10.jpg,Skyline_6117,snow,0,night,"dawn:12:01:47.085163, sunrise:12:33:07.626434, sunset:22:13:31.064296, dusk:22:44:52.275070",0.034961,0.001952,0.827273,0.036460,0.099354,0.827273,/home/csutter/DRIVE/site_analysis/outsideFinalTestDataset/images/Skyline_6117/snow/390_at_Lyell_Ave__Unknown__Skyline_6117_2022-01-25-00:00:10.jpg,17716,43.1645,-77.683375,2022,1,25,20220125,00:00:10,20220125,00:00:10 20220125,2022-01-25 00:00:10,2022-01-25 00:00:00,2022-01-24 22:00:00,22,2022,1,24,20220124,/home/csutter/AI2ES/cleaned/HRRR/2022/01/20220124_hrrr.t22z_02.parquet,"[43.16642726192929, -77.6681040222615]",1.260186,2022-01-24 22:00:00,2022-01-25 00:00:00,43.166427,-77.668104,263.8228,264.84235,0.00172,262.51434,82.9,-2.540636,0.959994,2.757503,0.009366,0.588,160.3884,0.0,100748.0,0.0,234.1,100.0,5259.7210,241.56229,0.0,500.0,2.715957,0.038349,0.002141,0.810533,0.039994,0.108983,snow,0.810533,True,1,0.827273,snow,0.010397,0.000000,0.888208,0.002007,0.099387,snow,0.888208,0.002403,0.000000,0.813725,0.120462,0.063409,snow,0.813725,0.025091,0.000000,0.798817,0.003876,0.172216,snow,0.798817,0.014845,0.000000,0.792453,0.045929,0.146773,snow,0.792453,"['snow', 'snow', 'snow', 'snow', 'snow']","[0.8272727272727273, 0.8882082695252682, 0.8137254901960784, 0.7988165680473372, 0.7924528301886793]","{'snow': ['m0', 'm1', 'm2', 'm3', 'm4']}",{'snow': 5},{'snow': 0.824095177046018},{'snow': 0.8882082695252682},0.017540,0.824095,0.041747,0.116228,0.000390,snow,0.824095,snow,snow,True,True,True,snow,align_avg_mode,True,True,5
1,1,16724,16724,16724,NAOuterTest,outerTest,390_at_Lyell_Ave__Unknown__Skyline_6117_2022-01-25-00:30:12.jpg,/home/csutter/DRIVE/site_analysis/outsideFinalTestDataset/images/Skyline_6117/snow/390_at_Lyell_Ave__Unknown__Skyline_6117_2022-01-25-00:30:12.jpg,Skyline_6117,snow,0,night,"dawn:12:01:47.085163, sunrise:12:33:07.626434, sunset:22:13:31.064296, dusk:22:44:52.275070",0.020566,0.000000,0.701258,0.020080,0.258097,0.701258,/home/csutter/DRIVE/site_analysis/outsideFinalTestDataset/images/Skyline_6117/snow/390_at_Lyell_Ave__Unknown__Skyline_6117_2022-01-25-00:30:12.jpg,17717,43.1645,-77.683375,2022,1,25,20220125,00:30:12,20220125,00:30:12 20220125,2022-01-25 00:30:12,2022-01-25 01:00:00,2022-01-24 23:00:00,23,2022,1,24,20220124,/home/csutter/AI2ES/cleaned/HRRR/2022/01/20220124_hrrr.t23z_02.parquet,"[43.16642726192929, -77.6681040222615]",1.260186,2022-01-24 23:00:00,2022-01-25 01:00:00,43.166427,-77.668104,265.1895,266.17490,0.00192,263.93730,86.7,-2.041184,2.278474,3.555572,0.007699,0.490,160.3884,0.0,100725.0,0.0,265.2,100.0,5257.7085,241.87479,0.0,500.0,3.059065,0.025528,0.000000,0.629176,0.024925,0.320371,snow,0.629176,True,1,0.701258,snow,0.007903,0.000000,0.831984,0.013075,0.147038,snow,0.831984,0.009922,0.002072,0.789474,0.064233,0.134299,snow,0.789474,0.017489,0.000000,0.798817,0.003478,0.180216,snow,0.798817,0.014085,0.001911,0.259730,0.011116,0.713158,wet,0.713158,"['snow', 'snow', 'snow', 'snow', 'wet']","[0.7012578616352201, 0.8319838056680162, 0.7894736842105263, 0.7988165680473372, 0.7131578947368421]","{'snow': ['m0', 'm1', 'm2', 'm3'], 'wet': ['m4']}","{'snow': 4, 'wet': 1}","{'snow': 0.7803829798902749, 'wet': 0.7131578947368421}",{'snow': 0.8319838056680162},0.013993,0.676252,0.022396,0.286562,0.000797,snow,0.676252,snow,snow,True,True,True,snow,align_avg_mode,True,True,4
2,2,16725,16725,16725,NAOuterTest,outerTest,390_at_Lyell_Ave__Unknown__Skyline_6117_2022-01-25-00:45:12.jpg,/home/csutter/DRIVE/site_analysis/outsideFinalTestDataset/images/Skyline_6117/snow/390_at_Lyell_Ave__Unknown__Skyline_6117_2022-01-25-00:45:12.jpg,Skyline_6117,snow,0,night,"dawn:12:01:47.085163, sunrise:12:33:07.626434, sunset:22:13:31.064296, dusk:22:44:52.275070",0.017977,0.000000,0.296005,0.019352,0.666667,0.666667,/home/csutter/DRIVE/site_analysis/outsideFinalTestDataset/images/Skyline_6117/snow/390_at_Lyell_Ave__Unknown__Skyline_6117_2022-01-25-00:45:12.jpg,17718,43.1645,-77.683375,2022,1,25,20220125,00:45:12,20220125,00:45:12 20220125,2022-01-25 00:45:12,2022-01-25 01:00:00,2022-01-24 23:00:00,23,2022,1,24,20220124,/home/csutter/AI2ES/cleaned/HRRR/2022/01/20220124_hrrr.t23z_02.parquet,"[43.16642726192929, -77.6681040222615]",1.260186,2022-01-24 23:00:00,2022-01-25 01:00:00,43.166427,-77.668104,265.1895,266.17490,0.00192,263.93730,86.7,-2.041184,2.278474,3.555572,0.007699,0.490,160.3884,0.0,100725.0,0.0,265.2,100.0,5257.7085,241.87479,0.0,500.0,3.059065,0.024636,0.000000,0.405656,0.026520,0.543188,wet,0.543188,False,0,0.666667,wet,0.016393,0.000384,0.577206,0.005746,0.400270,snow,0.577206,0.005160,0.001019,0.735507,0.071900,0.186414,snow,0.735507,0.052956,0.004757,0.506623,0.015333,0.420331,snow,0.506623,0.018665,0.002597,0.223425,0.014961,0.740351,wet,0.740351,"['wet', 'snow', 'snow', 'snow', 'wet']","[0.6666666666666666, 0.5772058823529411, 0.7355072463768116, 0.5066225165562914, 0.7403508771929825]","{'wet': ['m0', 'm4'], 'snow': ['m1', 'm2', 'm3']}","{'wet': 2, 'snow': 3}","{'wet': 0.7035087719298245, 'snow': 0.606445215095348}",{'wet': 0.7403508771929825},0.022230,0.467753,0.025458,0.482807,0.001752,wet,0.482807,snow,wet,False,True,False,wet,align_avg_maxConf,False,True,2
3,3,16726,16726,16726,NAOuterTest,outerTest,390_at_Lyell_Ave__Unknown__Skyline_6117_2022-01-25-01:15:13.jpg,/home/csutter/DRIVE/site_analysis/outsideFinalTestDataset/images/Skyline_6117/snow/390_at_Lyell_Ave__Unknown__Skyline_6117_2022-01-25-01:15:13.jpg,Skyline_6117,snow,0,night,"dawn:12:01:47.085163, sunrise:12:33:07.626434, sunset:22:13:31.064296, dusk:22:44:52.275070",0.061273,0.002687,0.701258,0.067079,0.167703,0.701258,/home/csutter/DRIVE/site_analysis/outsideFinalTestDataset/images/Skyline_6117/snow/390_at_Lyell_Ave__Unknown__Skyline_6117_2022-01-25-01:15:13.jpg,17719,43.1645,-77.683375,2022,1,25,20220125,01:15:13,20220125,01:15:13 20220125,2022-01-25 01:15:13,2022-01-25 01:00:00,2022-01-24 23:00:00,23,2022,1,24,20220124,/home/csutter/AI2ES/cleaned/HRRR/2022/01/20220124_hrrr.t23z_02.parquet,"[43.16642726192929, -77.6681040222615]",1.260186,2022-01-24 23:00:00,2022-01-25 01:00:00,43.166427,-77.668104,265.1895,266.17490,0.00192,263.93730,86.7,-2.041184,2.278474,3.555572,0.007699,0.490,160.3884,0.0,100725.0,0.0,265.2,100.0,5257.7085,241.87479,0.0,500.0,3.059065,0.065487,0.002872,0.680714,0.071692,0.179235,snow,0.680714,True,1,0.701258,snow,0.006152,0.000000,0.888208,0.006003,0.099636,snow,0.888208,0.002689,0.000000,0.881579,0.072408,0.043324,snow,0.881579,0.018510,0.000657,0.798817,0.006521,0.175496,snow,0.798817,0.014702,0.000000,0.625000,0.017040,0.343258,snow,0.625000,"['snow', 'snow', 'snow', 'snow', 'snow']","[0.7012578616352201, 0.8882082695252682, 0.881578947368421, 0.7988165680473372, 0.625]","{'snow': ['m0', 'm1', 'm2', 'm3', 'm4']}",{'snow': 5},{'snow': 0.7789723293152493},{'snow': 0.8882082695252682},0.020665,0.778972,0.033810,0.165884,0.000669,snow,0.778972,snow,snow,True,True,True,snow,align_avg_mode,True,True,5

In [17]:
df2 = df[["consistency","select_correct","img_orig"]].groupby(["consistency","select_correct"]).count().reset_index()

df2

   consistency  select_correct  img_orig
0            1           False        17
1            1            True        10
2            2           False       326
3            2            True       236
4            3           False       890
5            3            True       987
6            4           False      1015
7            4            True      1755
8            5           False      1720
9            5            True     14533